name: When release created
on:
  release:
    types: [created]

jobs:
  echo-release-title:
    runs-on: ubuntu-latest
    steps:
      - env:
        GITHUB_TOKEN: $${{ secrets.RELEASE_TOKEN }}
        run: |
          echo "The PR title ${{ github.event.pull_request.title }}"
