name: Release Automation
on:
  pull_request:
    types:
      - closed

jobs:
  if-release-pr-merged:
    if: |
      startsWith(github.event.pull_request.title, 'chore(main):release') && github.event.pull_request.merged == true &&
      github.event.pull_request.user.login == 'AnqiPang'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo  "This PR is opened by ${{ github.event.pull_request.user.login }}"
