name: When release created
on:
  release:
    types: [published]

jobs:
  echo-release-title:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The PR title ${{ github.event.pull_request.title }}"
