on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: $${{ secrets.RELEASE_TOKEN }}
        - uses: google-github-actions/release-please-action@v3
          with:
            release-type: go
            package-name: greeter
            changelog-types: >
              [
                {
                  "type":"feat",
                  "section":"Features",
                  "hidden":false
                },
                {
                  "type":"fix",
                  "section":"Bug Fixes",
                  "hidden":false
                },
                {
                  "type":"build",
                  "section":"Build System or External Dependencies",
                  "hidden":false
                }
              ]
            # Before we are at v1.0.0
            bump-minor-pre-major: true
