name: get release tag
on:
  workflow_dispatch:
jobs:
  get-latest-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.latesttag.outputs.tag }}
      version: ${{ steps.latestversion.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: 'Get the latest tag'
        id: latesttag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: v0.1.0
      - name: 'Convert tag to version'
        id: latestversion
        run: |
          version=${{ steps.latesttag.outputs.tag }}
          if [[  $version == v* ]]; then
            version="${version:1}"
          fi
          echo "version=$version" >> ${GITHUB_OUTPUT}
          
  print-version:
    needs: get-latest-tag
    runs-on: ubuntu-latest
    env: 
      TAG: ${{ needs.get-latest-tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
        with:
            ref: ${{ env.TAG }}
      - name: Print version
        run: |
          echo "get latest tag ${{ needs.get-latest-tag.outputs.tag }}"
          echo "get latest version $TAG"
  
  pr-to-homebrew:
    needs: print-version
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Open a pull request to homebrwe-cask
        run: |
          cd $(brew --repo homebrew/cask)
          pwd
        env:
          FINCH_VERSION: 0.3.0
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.MY_BOT_TOKEN }}
      - name: echo pwd
        run: pwd
      

