name: get release tag
on:
  workflow_dispatch:
jobs:
  get-latest-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.latesttag.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: 'Get the latest tag'
        id: latesttag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 0.1.0
  another-job:
    needs: get-latest-tag
    runs-on: ubuntu-latest
    steps:
      - run: echo "get latest tag ${{ needs.get-latest-tag.outputs.tag }}"

         
      

