name: Main

on: workflow_dispatch

jobs:
  get-latest-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.latesttag.outputs.tag }}
      version: ${{ steps.latestversion.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: 'Get the latest tag'
        id: latesttag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: 'Convert tag to version'
        id: latestversion
        run: |
          version=${{ steps.latesttag.outputs.tag }}
          if [ -z $version ]; then
            echo ERROR: Failed to get the latest tag
            exit 1
          fi
          if [[  $version == v* ]]; then
            version="${version:1}"
          fi
          echo "version=$version" >> ${GITHUB_OUTPUT}
  build:
    needs: get-latest-tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.get-latest-tag.outputs.tag }}
          files: Release.txt